apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  namespace: website
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: summit0102
            - name: POSTGRES_USER
              value: summit
            - name: POSTGRES_DB
              value: summit
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: website
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgre
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summit
  namespace: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summit
  template:
    metadata:
      labels:
        app: summit
    spec:
      containers:
        - name: summit
          image: ysoliveira/website-summit:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: summit
            - name: DB_PASSWORD
              value: pg1234
            - name: DB_USERNAME
              value: summit
            - name: DB_HOST
              value: postgre
---
apiVersion: v1
kind: Service
metadata:
  name: summit
  namespace: website
spec:
  selector:
    app: summit
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
