name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: ["main"]


jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Obtendo o código
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Construção da imagem Docker worker
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: false
          tags: |
            ysoliveira/website-summit:${{github.run_number}}
            ysoliveira/website-summit:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ysoliveira/website-summit:${{github.run_number}}
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: 0
          severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: "trivy-results.sarif"

      - name: Enviando a imagem
        run: |
          docker push ysoliveira/website-summit:${{github.run_number}}
          docker push ysoliveira/website-summit:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Obtendo o código
        uses: actions/checkout@v3

      - name: Configurando autenticação na GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurando contexto para o cluster GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: "product-summit"
          location: "us-central1"
          project_id: "constant-falcon-433116-h1"

      - name: Deploy to Kubernetes cluster
        run: |
          kubectl set image -f ./k8s/deployment.yaml ysoliveira/website-summit=ysoliveira/website-summit:${{github.run_number}}
          kubectl apply -f ./k8s/deployment.yaml
