name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      id: build
      run: |
        docker build -t ysoliveira/website-summit:${{ github.sha }} .

    - name: Push Docker image to registry
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push ysoliveira/website-summit:${{ github.sha }}

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/summit-deployment summit-container=ysoliveira/website-summit:${{ github.sha }} -n my-namespace
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Terraform Plan Review
      id: review
      uses: reviewdog/action-terraform@v1
      with:
        terraform_directory: './'
        plan_file: tfplan

    - name: Terraform Apply
      if: github.event_name == 'push' && github.actor == 'ysoliveira01'
      run: terraform apply -var="image_tag=${{ github.sha }}" -auto-approve tfplan
      env:
        TF_VAR_some_variable: ${{ secrets.TF_VAR_SOME_VARIABLE }}
